routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    return view('welcome');
    return redirect()->route('recipe.index');
});

Route::get('recipe/{id}/complete', [
    'uses' => 'RecipeController@complete',
    'as' => 'recipe.complete'
]);

Route::post('recipe/{id}/complete/store', [
    'uses' => 'RecipeController@storeComplete',
    'as' => 'recipe.complete.store'
]);

Route::get('ingredient/autocomplete', [
    'uses' => 'IngredientController@autoComplete',
    'as' => 'ingredient.autocomplete'
]);

Route::get('ingredient/add-to-form', [
    'uses' => 'IngredientController@addToForm',
    'as' => 'ingredient.form.add'
]);

Route::resource('recipe', 'RecipeController');
Route::resource('ingredient', 'IngredientController');

app/Helper.php
<?php namespace App;

class Helper
{
    public static function style($route)
    {
        return '<link media="all" type="text/css" rel="stylesheet" href="'.url($route).'?v='.filemtime(public_path($route)).'">';
    }

    public static function script($route)
    {
        return '<script src="'.url($route).'?v='.filemtime(public_path($route)).'"></script>';
    }

}

app/Ingredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'ingredients';

    protected $fillable = [
        'name'
    ];

}

app/Month.php
<?php

namespace App;


class Month
{
    public static function all()
    {
        return json_decode(json_encode(config('constants.months')));
    }
}

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'recipes';

    protected $fillable = [
        'season_id',
        'month_id',
        'name',
        'persons',
        'calories',
        'preparation_time_hours_total',
        'preparation_time_minutes_total',
        'preparation_time_hours_active',
        'preparation_time_minutes_active',
        'calories',
        'vegetarian',
        'vegan',
        'lactose_free',
        'gluten_free'
    ];

    public function images()
    {
        return $this->hasMany('App\RecipeImage');
    }
}

app/RecipeImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RecipeImage extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'recipe_images';

    protected $fillable = [
        'recipe_id',
        'file'
    ];

    public function recipe()
    {
        return $this->belongsTo('App\Recipe');
    }
}

app/RecipeStep.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RecipeStep extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'recipe_steps';

    protected $fillable = [
        'recipe_id'
    ];
}

app/Season.php
<?php

namespace App;

class Season
{
    public static function all()
    {
        return json_decode(json_encode(config('constants.seasons')));
    }
}

app/StepIngredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StepIngredient extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'step_ingredients';

    protected $fillable = [
        'step_id',
        'ingredient_id',
        'unit_id',
        'amount'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IngredientController.php
<?php namespace App\Http\Controllers;

use App\Ingredient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class IngredientController extends Controller {

    public function index()
    {
        dd('IngredientController index');
    }

    public function autoComplete(Request $request)
    {
        $input = $request->all();

        $suggestions = DB::table('ingredients')
            ->select('name as value', 'name as data')
            ->where('name', 'like', '%'.$input['query'].'%')
            ->take(6)
            ->get();

        $response = array(
            'query' => $input['query'],
            'suggestions' => $suggestions->toArray()
        );

        return $response;

    }

    public function addToForm()
    {
        return view('ingredient.form-input');
    }

}

app/Http/Controllers/RecipeController.php
<?php namespace App\Http\Controllers;

use App\Ingredient;
use App\Month;
use App\Recipe;
use App\RecipeStep;
use App\Season;
use Illuminate\Http\Request;
use Illuminate\View\View;

class RecipeController extends Controller {

    public function index()
    {
        return \view('recipe.index');
    }

    public function create()
    {
        return \view('recipe.create');
    }

    public function store(Request $request)
    {
        $input = $request->all();

        $input['vegetarian'] = array_key_exists('vegetarian', $input) ? 1 : 0;
        $input['vegan'] = array_key_exists('vegetarian', $input) ? 1 : 0;
        $input['lactose_free'] = array_key_exists('vegetarian', $input) ? 1 : 0;
        $input['gluten_free'] = array_key_exists('vegetarian', $input) ? 1 : 0;

        $recipe = Recipe::create($input);

        return redirect()->route('recipe.complete', [$recipe->id]);
    }

    public function complete($id)
    {
        $recipe = Recipe::find($id);

        return \view('recipe.complete')->with([
            'recipe' => $recipe
        ]);
    }

    public function storeComplete($id, Request $request)
    {
        $input = $request->all();

        dd($input);

//        $recipe_step = RecipeStep::create([
//            'recipe_id' => $id
//        ]);

        foreach ($input['ingredient'] as $new_ingredient){
            $ingredient = Ingredient::where('name', trim($new_ingredient['name']))->first();

            if(!$ingredient){

                $ingredient = Ingredient::create(array(
                    'name' => $new_ingredient['name']
                ));
            }

        }

//        TODO bind ingredient to step
//        TODO add units to constants?

        return redirect()->route('recipe.complete', [$id]);
    }

    public function edit($id)
    {
        $recipe = Recipe::find($id);

        return \view('recipe.edit')->with([
            'recipe' => $recipe
        ]);
    }

    public function update($id, Request $request)
    {

    }

    public function destroy($id)
    {

    }

}

resources/views/ingredient/form-input.blade.php
<div class="form-row">
    <div class="col">
        <div class="form-group">

            <div class="row">
                <div class="col-md-5">
                    <input type="text" name="ingredient[][name]" class="form-control autocomplete" placeholder="Nombre" />
                </div>

                <div class="col-md-3">
                    <input type="text" name="ingredient[][unit_id]" class="form-control" placeholder="Unidad" />
                </div>

                <div class="col-md-2">
                    <input type="text" name="ingredient[][amount]" class="form-control" placeholder="Cantidad" />
                </div>

                <div class="col-md-2">
                    <a class="btn btn-success add-ingredient" href="#">+</a>
                    <a class="btn btn-danger remove-ingredient" href="#">-</a>
                </div>
            </div>
        </div>
    </div>

</div>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    @section('meta')

    @show

    @section('css')
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {!! \App\Helper::style('css/style.css') !!}
    @show
</head>

<body>

@yield('content')

@section('js')
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
@show
</body>
</html>

resources/views/recipe/complete.blade.php
@extends('layout')

@section('meta')
    <meta name="description" content="Recetas">
    <meta name="title" content="Recetas">
    <title>Cocinillas | Editar receta</title>
@endsection

@section('css')
    @parent
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Editar receta</h1>

                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link"  href="{{ route('recipe.edit', [$recipe->id]) }}">General</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ route('recipe.complete', [$recipe->id]) }}">Paso 1</a>
                    </li>
                </ul>

                <form id="updateForm" data-autocomplete-url="{{ route('ingredient.autocomplete') }}" action="{{ route('recipe.complete.store', [$recipe->id]) }}" method="post" enctype="multipart/form-data">

                    <div class="tab-content">

                        <div class="tab-pane active">

                            <div class="form-body">

                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="_method" value="post" />

                                <div id="ingredients-container" data-url="{{ route('ingredient.form.add') }}">

                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group">

                                                <label>Ingredientes</label>

                                                <div class="row">
                                                    <div class="col-md-5">
                                                        <input type="text" name="ingredient[][name]" class="form-control autocomplete" placeholder="Nombre" />
                                                    </div>

                                                    <div class="col-md-3">
                                                        <input type="text" name="ingredient[][unit_id]" class="form-control" placeholder="Unidad" />
                                                    </div>

                                                    <div class="col-md-2">
                                                        <input type="text" name="ingredient[][amount]" class="form-control" placeholder="Cantidad" />
                                                    </div>

                                                    <div class="col-md-2">
                                                        <a class="btn btn-success add-ingredient" href="#">+</a>
                                                        <a class="btn btn-danger remove-ingredient" href="#">-</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                                <button type="submit" class="btn btn-primary">Guardar</button>

                            </div>

                        </div>

                    </div>

                </form>

            </div>
        </div>
    </div>


@endsection

@section('js')
    @parent
    {!! \App\Helper::script('js/jquery.autocomplete.min.js') !!}
    {!! \App\Helper::script('js/recipe/complete.js') !!}
@endsection

resources/views/recipe/create.blade.php
@extends('layout')

@section('meta')
    <meta name="description" content="Recetas">
    <meta name="title" content="Recetas">
    <title>Cocinillas | Nueva receta</title>
@endsection

@section('css')
    @parent
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Nueva receta</h1>

                <form action="{{  route('recipe.store') }}" method="post">

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="post" />

                    <div class="form-row">
                        <div class="col">
                            <div class="form-group">
                                <label for="name">Nombre</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="persons">N. de personas</label>
                            <input type="text" class="form-control" id="persons" name="persons">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="calories">Calorias por persona</label>
                            <input type="text" class="form-control" id="calories" name="calories">
                        </div>
                    </div>
                    <label>Tiempo Preparado Total</label>
                    <div class="form-row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="preparation_time_hours_total">Horas</label>
                                <select class="form-control" id="preparation_time_hours_total" name="preparation_time_hours_total" >
                                    @for($i = 0; $i <= 10; $i++)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="preparation_time_minutes_total">Minutos</label>
                                <select class="form-control" id="preparation_time_minutes_total" name="preparation_time_minutes_total">
                                    @for($i = 0; $i < 60; $i++)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>

                    <label>Tiempo activo</label>
                    <div class="form-row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="preparation_time_hours_active">Horas</label>
                                <select class="form-control" id="preparation_time_hours_active" name="preparation_time_hours_active" >
                                    @for($i = 0; $i <= 10; $i++)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="preparation_time_minutes_active">Minutos</label>
                                <select class="form-control" id="preparation_time_minutes_active" name="preparation_time_minutes_active">
                                    @for($i = 0; $i < 60; $i++)
                                        <option value="{{ $i }}">{{ $i }}</option>
                                    @endfor
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="vegetarian" name="vegetarian">
                                <label class="form-check-label" for="vegetarian">
                                    Vegetariana
                                </label>
                            </div>
                        </div>
                        <div class="form-group col-md-2">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="vegan" name="vegan">
                                <label class="form-check-label" for="vegan">
                                    Vegana
                                </label>
                            </div>
                        </div>
                        <div class="form-group col-md-2">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="lactose_free" name="lactose_free">
                                <label class="form-check-label" for="lactose_free">
                                    Sin lactosa
                                </label>
                            </div>
                        </div>
                        <div class="form-group col-md-2">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" id="gluten_free" name="gluten_free">
                                <label class="form-check-label" for="gluten_free">
                                    Sin gluten
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="season_id">Estacion</label>
                            <select class="form-control" id="season_id" name="season_id">
                                @foreach(\App\Season::all() as $season)
                                    <option value="{{ $season->id }}">{{ $season->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-2">
                            <label for="month_id">Estacion</label>
                            <select class="form-control" id="month_id" name="month_id">
                                @foreach(\App\Month::all() as $month)
                                    <option value="{{ $month->id }}">{{ $month->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('js')
    @parent
@endsection

resources/views/recipe/edit.blade.php
@extends('layout')

@section('meta')
    <meta name="description" content="Recetas">
    <meta name="title" content="Recetas">
    <title>Cocinillas | Editar receta</title>
@endsection

@section('css')
    @parent
@endsection

@section('content')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Editar receta</h1>

                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ route('recipe.edit', [$recipe->id]) }}">General</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('recipe.complete', [$recipe->id]) }}">Pasos</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>

@endsection

@section('js')
    @parent
@endsection

resources/views/recipe/index.blade.php
@extends('layout')

@section('meta')
    <meta name="description" content="Recetas">
    <meta name="title" content="Recetas">
    <title>Cocinillas | Recetas</title>
@endsection

@section('css')
    @parent
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Lista de recetas</h1>
                <a class="btn btn-primary" href="{{ route('recipe.create') }}">Nueva</a>
                <br>
                <br>
                @foreach(\App\Recipe::all() as $recipe)
                    <a href="{{ route('recipe.edit', [$recipe->id]) }}">{{ $recipe->name }}</a><br>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@section('js')
    @parent
@endsection